apiVersion: nve.netapp.io/v1
kind: NVEKubernetesCluster
metadata:
  name: kubernetes
spec:
  kubernetes:
    type: default
    version: 1.22.4
  replicas:
    onEvery: 1
  controlPlaneTemplate:
    spec:
      cpu: "2"
      memory: 4GB
  workerTemplate:
    spec:
      cpu: "2"
      memory: 4GB
