apiVersion: nve.netapp.io/v1
kind: NVEKubernetesCluster
metadata:
  name: kubernetes
spec:
  controlPlaneTemplate:
    spec:
      cpu: "2"
      image:
        marketplace: test-mp
        name: CentOS-Stream8-K8s
      memory: 4GB
  kubernetes:
    type: default
    version: 1.22.4
  replicas:
    onEvery: 1
  workerTemplate:
    spec:
      cpu: "2"
      memory: 4GB
      image:
        marketplace: test-mp
        name: CentOS-Stream8-K8s
