apiVersion: nve.netapp.io/v1
kind: NVEKubernetesCluster
metadata:
  name: kubernetes
spec:
  kubernetes:
    type: default
    version: 1.22.4
  replicas:
    onEvery: 1
  controlPlaneTemplate:
    cpu: "2"
    memory: 4GB
    image:
      name: CentOS-Stream8-K8s
      marketplace: test-mp
  workerTemplate:
    cpu: "2"
    memory: 4GB
