apiVersion: nve.netapp.io/v1
kind: NVEExternalStorage
metadata:
  name: "backup-target-2"
spec:
  protocol: "s3"
  s3target:
    bucket: "cggtestbucket"
    prefix: ""
    region: "us-east-2"   
    storageClass: "STANDARD"
    provider: "s3"
    encryption:
      protocol: "aes256"
      keyId: "key1"
