apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: datatest
  namespace: allclusters
spec:
  selector:
    matchLabels:
      env: dev
      location: rtp
      role: master

---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: datatest
  namespace: allclusters
spec:
  branch: master
  paths:
    - multi-cluster/configs/datatest
  repo: https://github.com/girishcx/fleet-examples
  targets:
    - clusterGroup: datatest
      name: datatest
