apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: my-cluster
  namespace: allclusters
spec:
  selector:
    matchLabels:
      env: dev
      location: rtp
      role: guest

---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: my-cluster
  namespace: allclusters
spec:
  targets:
    - clusterGroup: my-cluster
      name: my-cluster
  branch: master
  repo: https://github.com/girishcx/fleet-examples
  paths:
    - multi-cluster/configs/my-cluster
