apiVersion: nve.netapp.io/v1
kind: NVEVirtualMachine
metadata:
  name: newappx2
spec:
  template:
    spec:
      image:
        marketplace: test-mp
        name: CentOS-Stream8-K8s
      customization:
        sshKey: ssh-rsa
          AAAAB3NzaC1yc2EAAAADAQABAAABgQDDYryHcrQ42jJIPu5Vsy5NB8SpxOLIl4WC9gNbBFPnqxjwcuOChoAIa6ZEaiBrVQdAS37kuYtxRvL8rS21qEfGikf9wlZ7WTIMq0pr00cAi/MxV/Nf8lwu1Ud5blDMsltrc02D2xRj0tyeY8pkiJ8FIHYxM+X+DiU4HqRAaZg4r7Ufl7r8vKkN71DDJc0sdpmUD6wx/auhdrL7BoDidxBCd26Vmzouy+CAIco9uKgTEgwfToqKk3QiOaFOh2l1vCVVskYdNEX5guDBuPsnAJUMYVMLK5w7rEfTv4UWyKRwXp7o6FvjGXVjQUt4Z+fwn9SnjNXj79/mrPErbyCDY5Ed4kOUOmltkT6WObwRCPCVeHLGs7J+J5jmGgxf1ZGSONS8o19QTIopXV//w8DTrG1MRPsWuOJ4y2JRO8niyD/Txoy8yTH+1gVwpD9x95rS8WUJGN/jYJ9pv6QeSh6fD3Ig+LR1pxpnsnXT/AA+n/LOJaceHkQiUdbbwFHX9USxFI8=
          c5metal
        startScript: echo "Hi"
      cpu: "2"
      memory: 4GB
      network:
        - name: vnet-01
          qos:
            inbound:
              average: 100KB/s
              peak: 100KB/s
              burst: 100KB/s
            outbound:
              burst: 100KB/s
              peak: 100KB/s
              average: 100KB/s
